import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const sfPro = localFont({
  src: [
    {
      path: "../public/fonts/SF-Pro-Text-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Text-Semibold.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-sf-pro",
});

const garamond = localFont({
  src: [
    {
      path: "../public/fonts/ITC-Garamond-Std-Book-Narrow-Italic.woff2",
      weight: "500",
      style: "italic",
    },
  ],
  variable: "--font-garamond",
});

export const metadata: Metadata = {
  title: "Ej Liu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfPro.variable} ${garamond.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
